### PR TITLE
chore: add missing switch case for AutovalidateMode.onUnfocus

### PR DESCRIPTION
**Pull request by cyrilcolinet**
## Description

This allows the package to build with flutter version 3.24.x.
Just adding `onUnfocus` case on switch to remove compilation issue.

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Code Style Guide] and followed the process outlined there for submitting PRs.
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze` or `dart analyze`) does not report any problems on my PR.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I am authorized to release this code under the MIT License and agree to do so

## UI Change
Does your PR affect any UI screens?

- [ ] Yes, the relevant screens are included below.
- [x] No, there are no UI impacts with this PR.

[Code Style Guide]: https://github.com/peiffer-innovations/documentation/blob/main/CODE_STYLE.md
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning

### CODE REVIEW

**Comment by cyrilcolinet** [comment]
Hi @jpeiffer, this is a blocking changes for latest flutter version. Could you please review this ASAP ?
Thanks !

**Comment by davidcaseria** [comment]
Fixes #194

**Comment by aalloul** [comment]
Looking forward to this fix 🙏🏽

**Comment by cyrilcolinet** [comment]
Fixes #209

**Comment by cyrilcolinet** [comment]
Hi @Gustl22, you raise a good point; I have updated the PR with the suggested changes. 
I just tested it, and it works on 3.22.x.

I also mixed the changes to incorporate #212 changes inside.

**Comment by shockbytes** [comment]
Is there any estimate for this PR? This PR  is currently blocking us from updating to Flutter 3.24.

**Comment by MatijaNovosel** [comment]
Can anyone please merge this?

**Review by zwillianmattos — APPROVED** [review]

**Comment by cyrilcolinet** [comment]
Maybe someone else can review the code and approve (or suggest) the changes to accelerate the process maybe?
cc: @jpeiffer

**Review by jpeiffer — APPROVED** [review]

**Comment by jpeiffer** [comment]
Thanks for the PR!  Sorry, life's been busy but it's merged.

**Pull request merged**
